import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="絶望要塞風 円形ハッキング", layout="centered")

st.title("密室脱出：セキュリティ・ハッキング")
st.caption("中心のコアを守る回転レーザーを破壊し、セキュリティを解除せよ！")

# 構文エラーを絶対に起こさないよう、1行ずつのリストとして安全にJavaScriptを定義
html_lines = [
    '<div style="text-align: center; font-family: monospace;">',
    '    <canvas id="gameCanvas" style="background: #2a1015; border: 4px solid #b8a265; box-shadow: 0 0 20px #ff3333;"></canvas>',
    '    <div id="status" style="color: #d1c292; font-size: 22px; margin-top: 15px; height: 35px; font-weight: bold;"></div>',
    '    <button id="retryBtn" style="background: #110002; color: #d1c292; border: 2px solid #b8a265; padding: 10px 25px; font-size: 18px; font-family: monospace; cursor: pointer; margin-top: 10px; border-radius: 4px; box-shadow: 0 0 10px #ff0000;">',
    '        SYSTEM REBOOT (再生・再挑戦)',
    '    </button>',
    '</div>',
    '<script>',
    'const canvas = document.getElementById("gameCanvas");',
    'const ctx = canvas.getContext("2d");',
    'const statusDiv = document.getElementById("status");',
    'const retryBtn = document.getElementById("retryBtn");',
    'canvas.width = 600;',
    'canvas.height = 540;',
    'let animationId;',
    'let audioCtx = null;',
    'let gameActive = false;',
    'let paddleHeight = 12;',
    'let paddleWidth = 110;',
    'let paddleX;',
    'let rightPressed = false;',
    'let leftPressed = false;',
    'let ballRadius = 6;',
    'let x, y, dx, dy;',
    'let ballHistory = [];',
    'const centerX = canvas.width / 2;',
    'const centerY = canvas.height / 2 + 30;',
    'let bricks = [];',
    'let rotationAngle = 0;',
    'const rotationSpeed = 0.015;',
    'let startTime;',
    'const timeLimit = 60;',
    'let timeLeft = timeLimit;',
    'function playSound(type) {',
    '    if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)();',
    '    if (audioCtx.state === "suspended") audioCtx.resume();',
    '    const osc = audioCtx.createOscillator();',
    '    const gain = audioCtx.createGain();',
    '    osc.connect(gain); gain.connect(audioCtx.destination);',
    '    const now = audioCtx.currentTime;',
    '    if (type === "paddle") {',
    '        osc.type = "sine"; osc.frequency.setValueAtTime(500, now);',
    '        osc.frequency.exponentialRampToValueAtTime(800, now + 0.08);',
    '        gain.gain.setValueAtTime(0.2, now); gain.gain.exponentialRampToValueAtTime(0.01, now + 0.08);',
    '        osc.start(now); osc.stop(now + 0.08);',
    '    } else if (type === "brick") {',
    '        osc.type = "square"; osc.frequency.setValueAtTime(1000, now);',
    '        osc.frequency.setValueAtTime(1400, now + 0.05);',
    '        gain.gain.setValueAtTime(0.15, now); gain.gain.exponentialRampToValueAtTime(0.01, now + 0.08);',
    '        osc.start(now); osc.stop(now + 0.08);',
    '    } else if (type === "gameover") {',
    '        osc.type = "sawtooth"; osc.frequency.setValueAtTime(180, now);',
    '        osc.frequency.linearRampToValueAtTime(50, now + 0.8);',
    '        gain.gain.setValueAtTime(0.4, now); gain.gain.exponentialRampToValueAtTime(0.01, now + 0.8);',
    '        osc.start(now); osc.stop(now + 0.8);',
    '    } else if (type === "start") {',
    '        osc.type = "triangle"; osc.frequency.setValueAtTime(400, now);',
    '        osc.frequency.exponentialRampToValueAtTime(1200, now + 0.3);',
    '        gain.gain.setValueAtTime(0.2, now); gain.gain.exponentialRampToValueAtTime(0.01, now + 0.3);',
    '        osc.start(now); osc.stop(now + 0.3);',
    '    }',
    '}',
    'if (!window.keyEventsRegistered) {',
    '    document.addEventListener("keydown", (e) => {',
    '        if (e.key === "Right" || e.key === "ArrowRight") rightPressed = true;',
    '        else if (e.key === "Left" || e.key === "ArrowLeft") leftPressed = true;',
    '    }, false);',
    '    document.addEventListener("keyup", (e) => {',
    '        if (e.key === "Right" || e.key === "ArrowRight") rightPressed = false;',
    '        else if (e.key === "Left" || e.key === "ArrowLeft") leftPressed = false;',
    '    }, false);',
    '    window.keyEventsRegistered = true;',
    '}',
    'function initGame() {',
    '    if (animationId) cancelAnimationFrame(animationId);',
    '    playSound("start");',
    '    paddleX = (canvas.width - paddleWidth) / 2;',
    '    x = canvas.width / 2;',
    '    y = canvas.height - 50;',
    '    dx = 4;',
    '    dy = -5;',
    '    ballHistory = [];',
    '    rotationAngle = 0;',
    '    gameActive = true;',
    '    startTime = Date.now();',
    '    bricks = [];',
    '    for (let i = 0; i < 8; i++) {',
    '        bricks.push({ angleOffset: (Math.PI * 2 / 8) * i, radius: 90, width: 45, height: 18, status: 1 });',
    '    }',
    '    for (let i = 0; i < 10; i++) {',
    '        bricks.push({ angleOffset: (Math.PI * 2 / 10) * i, radius: 140, width: 55, height: 18, status: 1 });',
    '    }',
    '    statusDiv.innerHTML = "";',
    '    draw();',
    '}',
    'retryBtn.addEventListener("click", initGame);',
    'function collisionDetection() {',
    '    for (let i = 0; i < bricks.length; i++) {',
    '        let b = bricks[i];',
    '        if (b.status === 1) {',
    '            let currentAngle = b.angleOffset + rotationAngle;',
    '            let bX = centerX + Math.cos(currentAngle) * b.radius;',
    '            let bY = centerY + Math.sin(currentAngle) * b.radius;',
    '            let dist = Math.hypot(x - bX, y - bY);',
    '            if (dist < (b.width / 2 + ballRadius)) {',
    '                let angleToBall = Math.atan2(y - centerY, x - centerX);',
    '                dx = Math.cos(angleToBall) * 5;',
    '                dy = Math.sin(angleToBall) * 5;',
    '                b.status = 0;',
    '                playSound("brick");',
    '                if (bricks.every(brick => brick.status === 0)) {',
    '                    gameActive = false;',
    '                    statusDiv.innerHTML = "脱出成功！セキュリティ解除！";',
    '                    statusDiv.style.color = "#00ffff";',
    '                }',
    '                break;',
    '            }',
    '        }',
    '    }',
    '}',
    'function drawUI() {',
    '    ctx.strokeStyle = "#b8a265";',
    '    ctx.lineWidth = 2;',
    '    ctx.strokeRect(15, 15, canvas.width - 30, canvas.height - 30);',
    '    let destroyed = bricks.filter(b => b.status === 0).length;',
    '    let total = bricks.length;',
    '    let scoreStr = String(destroyed).padStart(3, "0");',
    '    ctx.fillStyle = "#d1c292";',
    '    ctx.font = "20px monospace";',
    '    ctx.textAlign = "left";',
    '    ctx.fillText("⚫︎ BALL 1", 40, 45);',
    '    ctx.fillText("SCORE " + scoreStr + "/" + total, 200, 45);',
    '    ctx.textAlign = "right";',
    '    ctx.fillText("TIMER " + timeLeft.toFixed(2), canvas.width - 40, 45);',
    '}',
    'function drawCore() {',
    '    ctx.beginPath();',
    '    ctx.arc(centerX, centerY, 30, 0, Math.PI * 2);',
    '    ctx.fillStyle = "#110002";',
    '    ctx.strokeStyle = "#ff3333";',
    '    ctx.lineWidth = 3;',
    '    ctx.fill();',
    '    ctx.stroke();',
    '    ctx.closePath();',
    '    ctx.beginPath();',
    '    ctx.arc(centerX, centerY, 15, 0, Math.PI * 2);',
    '    ctx.strokeStyle = "#ff3333";',
    '    ctx.lineWidth = 1;',
    '    ctx.stroke();',
    '    ctx.closePath();',
    '}',
    'function drawBricks() {',
    '    rotationAngle += rotationSpeed;',
    '    for (let i = 0; i < bricks.length; i++) {',
    '        let b = bricks[i];',
    '        if (b.status === 1) {',
    '            let currentAngle = b.angleOffset + rotationAngle;',
    '            let bX = centerX + Math.cos(currentAngle) * b.radius;',
    '            let bY = centerY + Math.sin(currentAngle) * b.radius;',
    '            ctx.save();',
    '            ctx.translate(bX, bY);',
    '            ctx.rotate(currentAngle + Math.PI/2);',
    '            ctx.beginPath();',
    '            ctx.rect(-b.width / 2, -b.height / 2, b.width, b.height);',
    '            ctx.fillStyle = "rgba(209, 194, 146, 0.8)";',
    '            ctx.strokeStyle = "#fffbdf";',
    '            ctx.lineWidth = 1.5;',
    '            ctx.fill();',
    '            ctx.stroke();',
    '            ctx.closePath();',
    '            ctx.restore();',
    '        }',
    '    }',
    '}',
    'function drawBall() {',
    '    ballHistory.push({ x: x, y: y });',
    '    if (ballHistory.length > 8) ballHistory.shift();',
    '    for (let i = 0; i < ballHistory.length; i++) {',
    '        ctx.beginPath();',
    '        ctx.arc(ballHistory[i].x, ballHistory[i].y, ballRadius * (i / ballHistory.length), 0, Math.PI * 2);',
    '        ctx.fillStyle = "rgba(255, 255, 255, " + (i / ballHistory.length) * 0.4 + ")";',
    '        ctx.fill();',
    '        ctx.closePath();',
    '    }',
    '    ctx.beginPath();',
    '    ctx.arc(x, y, ballRadius, 0, Math.PI * 2);',
    '    ctx.fillStyle = "#ffffff";',
    '    ctx.fill();',
    '    ctx.closePath();',
    '}',
    'function drawPaddle() {',
    '    ctx.save();',
    '    let grad = ctx.createLinearGradient(paddleX, canvas.height - 35, paddleX, canvas.height - 35 + paddleHeight);',
    '    grad.addColorStop(0, "#ffffff");',
    '    grad.addColorStop(0.5, "#aaff00");',
    '    grad.addColorStop(1, "#66aa00");',
    '    ctx.beginPath();',
    '    ctx.rect(paddleX, canvas.height - 35, paddleWidth, paddleHeight);',
    '    ctx.fillStyle = grad;',
    '    ctx.shadowBlur = 10;',
    '    ctx.shadowColor = "#aaff00";',
    '    ctx.fill();',
    '    ctx.restore();',
    '}',
    'function draw() {',
    '    ctx.clearRect(0, 0, canvas.width, canvas.height);',
    '    ctx.fillStyle = "#200a0d";',
    '    ctx.fillRect(0, 0, canvas.width, canvas.height);',
    '    if (gameActive) {',
